# アクション名
name: Test

# タイミングを指定
on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    javascriptCheck:
        name: JavaScript Check on Ubuntu
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - uses: actions/cache@v2
              with:
                  path: ${YARN_CACHE_FOLDER}
                  key: ${{ runner.os }}-yarn-cache-v1
            - run: yarn
            - name: Run check
              run: yarn romeCheck
    javascriptTest:
        needs: javascriptCheck
        name: JavaScript Test on Ubuntu
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - uses: actions/cache@v2
              with:
                  path: ${YARN_CACHE_FOLDER}
                  key: ${{ runner.os }}-yarn-cache-v1
            - run: yarn
            - name: Run Test
              run: yarn test
